### ISSUE TITLE
Missing browser implementation

### ISSUE THREAD

**Issue by feross** [creationix/sha1-digest#1]
Would you accept a PR to use `sha.js` by @dominictarr as the browser implementation of SHA1?

I think I can include it in a way that only the SHA-1 implementation gets bundled for browsers (saving on file size).

**Comment by dominictarr** [comment]
actually, @creationix already has a sha implementation https://github.com/creationix/git-sha1
I benchmarked it http://dominictarr.github.io/crypto-bench/
and it's a bit faster than my sha.js

**Comment by feross** [comment]
Nice! `git-sha1` looks great! I'll just use it directly. Looks like there's no need for `sha1-digest`, right?

**Comment by feross** [comment]
Wow, `git-sha1` is excellent! It's great that it works in node so I can use the same module in both places. But the real killer is the bundle size difference. Take a look!

``` bash
$ browserify -r crypto | wc -c
   84261
$ browserify -r git-sha1 | wc -c
    6499
```

Great work @creationix!
